### ISSUE TITLE
Unlikely term in calculation of "seuil"

### ISSUE THREAD

**Issue by eutboljo** [Jterrettaz/sunduration#2]
The calculation of "seuil" reads like this:
`seuil = (0.7 + 0.085 * cos((pi / 180) * 360 * dayofyear / 365)) * 1080 * pow((sin(pi / 180) * hauteur_soleil), 1.25)`

This contains a strange sin()-term in the pow()-term:
`pow( ( sin(pi / 180) * hauteur_soleil ), 1.25 ) `

`sin(pi/180)` is just a constant, while this constant is only muliplied with `hauteur_soleil`, which is given in degrees: Strange to me.

By moving the second parentheses inside the sin()-term:
`pow( sin( (pi / 180) * hauteur_soleil ), 1.25 )`
the sin()-term simply calculates the sine of `hauteur-soleil` transformed into in radians, wich seem to be much more likely.

I have seen this strange parenthesis setting already in the original Excel sheet. Therefore I am not absolute certain that this is an error, but I would still expect so.

**Comment by Jterrettaz** [comment]
Thanks for your comment, and I think you are right.  
One problem observed with the formula as it is in the Excel file is that threshold values during summer are too high, and I had to change the published empirical factors from 0.73 and 0.06. to 0.7 and 0.085.
With the parenthesis at the right place, the threshold at the middle of the day is now lower and this problem disappear with the original empirical factors.

**Comment by Jterrettaz** [comment]
I have corrected the formula and moved to the original empirical factors
