### ISSUE TITLE
Bug in line 6 of sunduration.py

### ISSUE THREAD

**Issue by Millardiang** [Jterrettaz/sunduration#3]
Currently line 6 in sunduration.py reads: -

from weewx.wxengine import StdService

wxengine.py does not exist, it should read: -

from weewx.engine import StdService

**Comment by Jterrettaz** [comment]
Sorry, but wxengine.py (located in the weewx directory) exists since in least version 3.8 !  
Which version of weewx are you running ?

**Comment by Millardiang** [comment]
5.02https://claydonsweather.org.ukOn 27 May 2024, at 08:16, Jterrettaz ***@***.***> wrote:﻿
Sorry, but wxengine.py (located in the weewx folder) exists since in least version 3.8 !
Which version of weewx are you running ?

**Comment by Jterrettaz** [comment]
As I said, wxengine.py exists in V5.0.2 :  https://github.com/weewx/weewx/tree/master/src/weewx

**Comment by Millardiang** [comment]
My apologies. Yes you are correct. However for some strange reason it was missing from my WeeWX 5.02 pip install. I have adapted your code to work with my own template, the interesting thing is that it appeared to work perfectly well without wxengine.py being present on my system.RegardsIMhttps://claydonsweather.org.ukOn 27 May 2024, at 09:31, Jterrettaz ***@***.***> wrote:﻿
As I said, wxengine.py exists in V5.0.2 :  https://github.com/weewx/weewx/tree/master/src/weewx

**Comment by Jterrettaz** [comment]
In fact, wxengine.py is just a very short script that redirect to engine.py for backwards compatibility.  So if you changed your version to look directly at engine.py, it will work also !
